---
- hosts: os
  name: running or stopping the required the services
  tasks: 
  
  - name: making sure the back-up prerequisites are done
    file:
      path: /usr/share/cis
      state: directory
      owner: root
      group: root
      mode: '0744'
  - file:
      path: /usr/share/cis/tasks-status.yml
      owner: root
      group: root
      mode: '0644'
      state: touch

  - name: rhnsd
    systemd:
       name: rhnsd
       enabled: no
       state: stopped
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - pause:
     seconds: 3
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status20: {{ ansible_facts['changed'] }} ##rhnsd service action:stop "
        state: present

  
  - name: Start service chargen-dgram, if not running
    service:
      name: chargen-dgram
      state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - pause:
     seconds: 3
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status21: {{ ansible_facts['changed'] }} ##chargen-dgram service action:stop "
        state: present
  

  - name: Start service chargen-stream, if not running
    service:
      name: chargen-stream
      state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status22: {{ ansible_facts['changed'] }} ##chargen-stream service action:stop "
        state: present



  - name: Start service daytime-dgram, if not running
    service:
     name: daytime-dgram
     state: stopped
    ignore_errors: yes
    register: ansible_facts

  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status23: {{ ansible_facts['changed'] }} ##daytime-dgram service action:stop "
        state: present

  - name: Start service daytime-stream, if not running
    service:
      name: daytime-stream
      state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status24: {{ ansible_facts['changed'] }} ##dgram service action:stop "
        state: present

  - name: Start service discard-stream, if not running
    service:
      name: discard-stream
      state: stopped
    ignore_errors: yes 
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status25: {{ ansible_facts['changed'] }} ##discard-stream service action:stop "
        state: present

  - name: Start service daytime-dgram, if not running
    service:
      name: discard-dgram
      state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status26: {{ ansible_facts['changed'] }} ##discard-dgram service action:stop "
        state: present

  - name: Start service echo-dgram, if not running
    service:
      name: echo-dgram
      state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status27: {{ ansible_facts['changed'] }} ##echo-dgram service action:stop "
        state: present

  - name: Start service echo-stream, if not running
    service:
      name: echo-stream
      state: stopped
    ignore_errors: yes

  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status28: {{ ansible_facts['changed'] }} ##echo-stream service action:stop "
        state: present

  - name: Start service time-stream, if not running
    service:
      name: time-stream
      state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status29: {{ ansible_facts['changed'] }} ##time-strean service action:stop "
        state: present


  - name: Start service time-dgram, if not running
    service:
      name: time-dgram
      state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status30: {{ ansible_facts['changed'] }} ##time-dgram service action:stop "
        state: present
 
  - name: Stop service tftp, if running
    service:
      name: tftp
      state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status31: {{ ansible_facts['changed'] }} ##tftp service action:stop "
        state: present

 
  - name: xinetd
    systemd:
       name: xinetd
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status32: {{ ansible_facts['changed'] }} ##xinetd service action:stop "
        state: present

  - name: disable avahi-daemon Service
    systemd:
       name: avahi-daemon
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible-facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status33: {{ ansible_facts['changed'] }} ##avahi-daemon service action:stop "
        state: present

  - name: disable cups Service
    systemd:
       name: cups
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status34: {{ ansible_facts['changed'] }} ##cups service action:stop "
        state: present


  - name: disable dhcpd Service
    systemd:
       name: dhcpd
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status35: {{ ansible_facts['changed'] }} ##dhcpd service action:stop "
        state: present


  - name: disable slapd Service
    systemd:
       name: slapd
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status36: {{ ansible_facts['changed'] }} ##slapd service action:stop "
        state: present


  - name: disable nfs Service
    systemd:
       name: nfs
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible-facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status37: {{ ansible_facts['changed'] }} ##nfs service action:stop "
        state: present


  - name: disable nfs-server Service
    systemd:
       name: nfs-server
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status38: {{ ansible_facts['changed'] }} ##nfs-server service action:stop "
        state: present
  

  - name: disable rpcbind Service
    systemd:
       name: rpcbind
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status39: {{ ansible_facts['changed'] }} ##rpcbind service action:stop "
        state: present


  - name: disable named Service
    systemd:
       name: named
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status40: {{ ansible_facts['changed'] }} ##named service action:stop "
        state: present

  - name: disable vsftpd Service
    systemd:
       name: vsftpd
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status41: {{ ansible_facts['changed'] }} ##vsftpd service action:stop "
        state: present


  - name: disable httpd Service
    systemd:
       name: httpd
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status42: {{ ansible_facts['changed'] }} ##httpd service action:stop "
        state: present

  - name: disable dovecot Service
    systemd:
       name: dovecot
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status43: {{ ansible_facts['changed'] }} ##dovecot service action:stop "
        state: present


  - name: disable smb Service
    systemd:
       name: smb
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
       path: /usr/share/cis/tasks-status.yml
       line: "status44: {{ ansible_facts['changed'] }} ##smb service action:stop "
       state: present


  - name: disable squid Service
    systemd:
       name: squid
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible-facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status45: {{ ansible_facts['changed'] }} ##squid service action:stop "
        state: present

  - name: disable snmpd Service
    systemd:
       name: snmpd
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status46: {{ ansible_facts['changed'] }} ##snmpd service action:stop "
        state: present

  - name: disable ypserv Service
    systemd:
       name: ypserv
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status47: {{ ansible_facts['changed'] }} ##ypserv service action:stop "
        state: present
 
  - name: disable rsh.socket  Service
    systemd:
       name: rsh.socket
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status48: {{ ansible_facts['changed'] }} ##rsh.socket service action:stop "
        state: present


  - name: disable rlogin.socket  Service
    systemd:
       name: rlogin.socket
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status49: {{ ansible_facts['changed'] }} ##rlogin.socker service action:stop "
        state: present

  - name: disable rexec.socket  Service
    systemd:
       name: rexec.socket
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status50: {{ ansible_facts['changed'] }} ##rexec.socket action:stop"
        state: present
  
  - name: disable ntalk  Service
    systemd:
       name: ntalk
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status51: {{ ansible_facts['changed'] }} ##ntalk service action:stop "
        state: present




  - name: disable telnet.socket  Service
    systemd:
       name: telnet.socket
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
     msg: " the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status52: {{ ansible_facts['changed'] }} ##telnet.socket service action:stop "
        state: present


  - name: disable tftp.socket  Service
    systemd:
       name: tftp.socket
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
      msg: "the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status53: {{ ansible_facts['changed'] }} ##tftp service action:stop "
        state: present

  - name: disable rsyncd  Service
    systemd:
       name: rsyncd
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
        msg: "the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status54: {{ ansible_facts['changed'] }} ##rsyncd service action:stop "
        state: present
 
    
  - name: disable rsyncd  Service
    systemd:
       name: autofs
       enabled: no
       state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
        msg: "the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status55: {{ ansible_facts['changed'] }} ##autofs service action:stop "
        state: present



  - name: enable auditd  Service
    systemd:
       name: auditd
       enabled: yes
       #state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
        msg: "the data are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
        path: /usr/share/cis/tasks-status.yml
        line: "status56: {{ ansible_facts['changed'] }} ##auditd service action:enable "
        state: present

  - name: enable rsyslog  Service
    systemd:
       name: rsyslog
       enabled: yes
    ignore_errors: yes
    register: ansible_facts
  - debug:
       msg: "the data are:  {{ ansible_facts['changed'] }}"
  
  - pause:
       seconds: 5
  - lineinfile:
       path: /usr/share/cis/tasks-status.yml
       line: "status57: {{ ansible_facts['changed'] }} ##rsyslog service action:enable "
       state: present
    #notify:
       #- name: reload the rsyslogd configuration
  - name: enable syslog-ng  Service
    systemd:
       name: syslog-ng
       enabled: yes
       #state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
       msg: "the status for syslog-ng service are:  {{ ansible_facts['changed'] }}"
  - lineinfile:
       path: /usr/share/cis/tasks-status.yml
       line: "status58: {{ ansible_facts['changed'] }} ##syslog-ng service action:enable "
       state: present
 
  - name: Ensure cron daemon is enabled
    systemd:
       name: crond
       enabled: yes
       #state: stopped
    ignore_errors: yes
    register: ansible_facts
  - debug:
       msg: "the data are:  {{ ansible_facts['changed'] }}"
  - pause:
       seconds: 3
  - lineinfile:
       path: /usr/share/cis/tasks-status.yml
       line: "status59: {{ ansible_facts['changed'] }} ##crond service action:enable "
       state: present


  ################
  ################   
  - name: check whether firewalld or iptables is being used by the system
    shell: yum list installed | grep iptables-services
    register: iptables_check
    ignore_errors: yes
  - debug:
      msg: "Iptables is installed"
    when: iptables_check.stdout != ""
  - shell: yum list installed | grep firewalld
    register: firewalld_check
  - debug: 
      msg: "firewalld is installed"
    when: firewalld_check
 
 
  #handlers:
    #- name: reload the rsyslogd configuration
       #shell: pkill -HUP rsyslogd

    
